### ISSUE TITLE
A Cpp program that generates the Fibonacci series up to a given input number.

### ISSUE THREAD

**Issue by R0Y15** [Astha369/CPP_Problems#13]
I'd like to add my contribution to the above problem statement. please assign this to me

**Comment by R0Y15** [comment]
please label this as hacktoberfest

**Comment by Astha369** [comment]
It's done.

**Comment by aadityavvij** [comment]
Please assign this problem to me

**Comment by Raghu1124** [comment]
Please assign me this issue, I am currently working on DSA, cpp, so it will be a good experience for me to work on it

**Comment by Rohansaini1512** [comment]
@Astha369 please assign this issue to me
