### ISSUE TITLE
Query related to pull request

### ISSUE THREAD

**Issue by Myworld21** [Astha369/CPP_Problems#19]
Hey @Astha369 I have a doubt. Can I create more than one pull requests?

**Comment by Astha369** [comment]
Hey @Myworld21 Yes, you can create multiple PRs, just after the previous ones have been merged.

**Comment by Myworld21** [comment]
> Hey @Myworld21 Yes, you can create multiple PRs, just after the previous ones have been merged.

Sure, thanks!

**Comment by Myworld21** [comment]
> Hey @Myworld21 Yes, you can create multiple PRs, just after the previous ones have been merged.

You had merged my previous one but hacktoberfest has put as waiting for 7 days on its page. So, I should contribute after 7 days or I can do today also?

**Comment by Astha369** [comment]
Hey @Myworld21 I'm glad that your PR is under the waiting period by Hacktoberfest, this means that after 7 days of waiting time, your contribution will be counted in the participation. However, feel free to contribute as much as you want without bothering about the waiting time or any other factor. 

Do contact me in case the waiting time stops or the repo shows excluded. 

Happy Contributing!

**Comment by Myworld21** [comment]
> Hey @Myworld21 I'm glad that your PR is under the waiting period by Hacktoberfest, this means that after 7 days of waiting time, your contribution will be counted in the participation. However, feel free to contribute as much as you want without bothering about the waiting time or any other factor.
> 
> Do contact me in case the waiting time stops or the repo shows excluded.
> 
> Happy Contributing!

Sure....Thank You!
