### ISSUE TITLE
Create Sorting Algos

### ISSUE THREAD

**Issue by Astha369** [Astha369/CPP_Problems#22]
Anyone who is up for creating sorting algos in cpp:
1. Radix Sort
2. Merge Sort
3. Quick Sort
4. Heap Sort

**Comment by Myworld21** [comment]
Hey @Astha369 Please assign me this issue. I am working on Data structures and Algorithms using CPP from a long time. So, you can consider me suitable for this task. Thank you!

**Comment by Astha369** [comment]
You can work on these algorithms @Myworld21

**Comment by Myworld21** [comment]
> You can work on these algorithms @Myworld21

Sure! Thanks.

**Comment by Raghu1124** [comment]
@Astha369 can you please assign me this issue, I am currently preparing for DSA, so it will be a good experience for me to work on it

**Comment by M-Elsayed9** [comment]
Can I please be assigned this issue?

**Comment by Astha369** [comment]
Yeah sure, @M-Elsayed9 @Raghu1124 there are various algos for sorting, you can work on them.

**Comment by Harshs0891** [comment]
Can You Plz assign this issue to me

**Comment by Rohansaini1512** [comment]
@Astha369 Can you please assign this issue to me Currently i am preparing DSA

**Comment by Aaryan-9** [comment]
@Astha369 Can you please assign this issue to me Currently i am Strengthening DSA, in cpp, so it would help me:)

**Comment by Myworld21** [comment]
> You can work on these algorithms @Myworld21

@Astha369 I need to create separate pull requests for all four sorting algorithms or all in one only?

**Comment by Astha369** [comment]
@Myworld21 that depends on you.

**Comment by Astha369** [comment]
@Harshs0891 @Rohansaini1512 @Aaryan-9 I really appreciate your enthusiasm for the contribution but I already have assigned three to this issue. I'll be opening new ones here as well, you can contribute to them, they will also be beginner level.

**Comment by Myworld21** [comment]
> @Myworld21 that depends on you.

Thank You @Astha369 I have compiled all four...I will be pulling the request separately soon.

**Comment by Myworld21** [comment]
> @Myworld21 that depends on you.

Thank you @Astha369 I will be pulling request for all four algorithms separately soon, I have compiled all those.

**Comment by Astha369** [comment]
The repo has all the sorting algos, if there is anyone who wanna add any feel free to create PR directly, as I'm closing this issue. Thank you contributing.
