### ISSUE TITLE
String Manipulation

### ISSUE THREAD

**Issue by Astha369** [Astha369/CPP_Problems#26]
1. Substring of a String (A substring is a contiguous part of a string, i.e., a string inside another string.)

2. Subsequence of a String (A subsequence is a sequence that can be derived from another sequence by removing zero or more elements, without changing the order of the remaining elements.)

3. Palindrome String (A string is said to be a palindrome if the reverse of the string is the same as the string. )

**Comment by Harshs0891** [comment]
Can you plz elaborate a little bit about the first and second question how the algorithm should be written.I am interested in solving this issue.Thank You:)

**Comment by Aaryan-9** [comment]
I am interested for this, as I am strengthening my DSA, could you please assign me this one, and elaborate a litttle bit on the 2nd one:)

**Comment by statst** [comment]
Hi intrested in this let me know if I can pick up.

**Comment by statst** [comment]
> Hi intrested in this let me know if I can pick up.

Hi Astha,
I have completed the solutions. I am unable to push changes. Could you please give me the permission to push changes and add pull request.

**Comment by Astha369** [comment]
Hi @statst did you fork the repo?

**Comment by Ankit-0009** [comment]
Please assign this problem to me. 
I want to ask a question that I have to wirte all three codes in a single file or in different files.
Thank you.

**Comment by statst** [comment]
> Hi @statst did you fork the repo?

Thanks! Added PR, please review
