### ISSUE TITLE
Paths colliding due to case sensitivity

### ISSUE THREAD

**Issue by PuruSinghvi** [Astha369/CPP_Problems#42]
the files quick_sort.cpp and Quick_sort.cpp are colliding due to the same name and only one from the same colliding group is in the working tree when cloned on my system. This will also be happening with many other users, can you please change name of one of them?

**Comment by Astha369** [comment]
Hey @PuruSinghvi you can pull the changes, I've renamed it. Thanks for informing though !

Happy Contributing!
