### ISSUE TITLE
Regarding permission to work on an issue

### ISSUE THREAD

**Issue by Myworld21** [Astha369/CPP_Problems#46]
Hey @Astha369 Can I work on the code "TO DETECT THE CYCLE IN LINKED LIST" ?

**Comment by Astha369** [comment]
Yeah, sure, I've assigned it to you.

**Comment by Myworld21** [comment]
> Yeah, sure, I've assigned it to you.
Thank You

**Comment by Myworld21** [comment]
> Yeah, sure, I've assigned it to you.

Can you please add Hacktoberfest-accepted label to this issue?
