### ISSUE TITLE
Max Dot Product of Two Subsequence - leetcode 8th Oct Daily

### ISSUE THREAD

**Issue by adit26data** [Astha369/CPP_Problems#48]
@Astha369 Can you assign me this with hacktoberfest accepted label so that I can make  a PR?

**Comment by Astha369** [comment]
Name the file as leetcode problem and date.

**Comment by Astha369** [comment]
@adit26data name the file u will commit as leetcode problem and date of the POTD

**Comment by adit26data** [comment]
@Astha369 I have made a pull request as you requested. Please merge it with the hacktoberfest accepted label

**Comment by adit26data** [comment]
@Astha369 thank you for merging. However it is not showing accepted on Hacktoberfest site. Is there an issue on my part or yours or will it take time?

**Comment by HarshitaShrivas66** [comment]
Hello, I would really appreciate contributing to this repository by adding a code
 @Astha369 please assign this task to me.

**Comment by HarshitaShrivas66** [comment]
@Astha369 please accept my pull request

**Comment by HarshitaShrivas66** [comment]
#74

**Comment by HarshitaShrivas66** [comment]
Thank you @Astha369 for merging.
