### ISSUE TITLE
Reverse Integer

### ISSUE THREAD

**Issue by Manul28** [Astha369/CPP_Problems#69]
@Astha369 Can you assign me this with hacktoberfest accepted label so that I can make a PR?

I have already made a PR can you please accept that?

**Comment by Ankit-0009** [comment]
Please assign this problem to me and kindly add hacktoberfest accepted label 
Thank You

**Comment by AKG1301** [comment]
@Manul28 , can you please assign this task to me?

**Comment by statst** [comment]
@Astha369 issues you created are really useful for DSA practice, could you please create and assign me any new issue if you are going to create

**Comment by Astha369** [comment]
Hey @statst thank you for your words. I'll create a few today and also you can create issues to work on yourself.

**Comment by Manul28** [comment]
Not a issue at all

**Comment by HarshitaShrivas66** [comment]
hey!! @Astha369  please accept and merge my pull request
