### ISSUE TITLE
Word pattern check - leetcode challenge

### ISSUE THREAD

**Issue by aggarwal-tanushree** [Astha369/CPP_Problems#95]
@Astha369 kindly assign this issue to me and add _hacktoberfest-accepted_ label

**Comment by aggarwal-tanushree** [comment]
@Astha369 [PR](https://github.com/Astha369/CPP_Problems/pull/97 ) created for this issue. Please check and merge.
Thanks,
Tanushree A

**Comment by Astha369** [comment]
Hey @aggarwal-tanushree thank you for contributing to this repo!

Keep learning and happy contributing!
